security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: mail

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_seconnecter
        check_path: app_seconnecter
        username_parameter: mail
        password_parameter: mdp
        enable_csrf: true
      custom_authenticators:
        - App\Security\LoginAuthenticator # Authentificateur formulaire
      logout:
        path: /logout
        target: app_seconnecter
        csrf_token_id: logout

  access_control:
    - { path: ^/app_back_office, roles: [ROLE_ADMIN] } # Accès Admin
    - { path: ^/app_home, roles: ROLE_CLIENT } # Page réservée aux clients
    - { path: ^/connect/google, roles: PUBLIC_ACCESS } # Permet à tout le monde d'utiliser Google Login
    - { path: ^/seconnecter, roles: PUBLIC_ACCESS } # Page de connexion accessible à tous
    - { path: ^/sinscrire, roles: PUBLIC_ACCESS } # Inscription accessible à tous
    - { path: ^/, roles: PUBLIC_ACCESS } # Page d'accueil accessible à tous
