# config/packages/security.yaml

security:
  # Activer le gestionnaire d'authentification pour utiliser des authenticators personnalisés
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: mail

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_seconnecter
        check_path: app_seconnecter
        username_parameter: mail
        password_parameter: mdp
        enable_csrf: true

      # Utilisation de l'authenticator personnalisé
      custom_authenticators:
        - App\Security\GoogleAuthenticator
        - App\Security\LoginAuthenticator

      # Redirection vers la page d'accès refusé
      access_denied_url: /access-denied

      logout:
        path: /logout
        target: app_seconnecter
        csrf_token_id: logout

  access_control:
    - { path: ^/back/, roles: [ROLE_ADMIN] }
    - { path: ^/app_home, roles: ROLE_CLIENT }
    - { path: ^/connect/google/, roles: PUBLIC_ACCESS }
    - { path: ^/seconnecter, roles: PUBLIC_ACCESS }
    - { path: ^/sinscrire, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: PUBLIC_ACCESS }
    - { path: ^/user/profiler, roles: ROLE_CLIENT }
