parameters:
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'

services:
    stripe.client:
        class: Stripe\StripeClient
        factory: ['Stripe\StripeClient', 'new']
        arguments: ['%stripe_secret_key%']

    # Alias for autowiring
    Stripe\StripeClient: '@stripe.client' 