parameters:
  photos_directory: "%kernel.project_dir%/public/uploads/photos"
  profile_pictures_directory: "%kernel.project_dir%/public/uploads/profile"

services:
  # Configuration par défaut pour les services dans ce fichier
  _defaults:
    autowire: true # Injecte automatiquement les dépendances
    autoconfigure: true # Enregistre automatiquement certains services (commandes, subscribers, etc.)

  # Permet d'utiliser les classes situées dans src/ comme services
  # Chaque classe aura pour identifiant son nom de classe complet
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Vous pouvez ajouter d'autres définitions de services ici, si nécessaire.
